- hosts: mysql app gitlab runner monitoring
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    k55
  roles:
   - install_node_exporter

  environment:
     http_proxy: http://w00ps.ru:8118
     https_proxy: http://w00ps.ru:8118
