- hosts: app
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    k55
  vars:
    - domain: "w00ps.ru"
    - download_url: "http://wordpress.org/latest.tar.gz"
    - wpdirectory: "/var/www"
 
  roles:
   - nginx
   - php
   - wordpress

  environment:
     http_proxy: http://w00ps.ru:8118
     https_proxy: http://w00ps.ru:8118
